#!/usr/bin/env python3
""" Generate a response from the provided LLM and prompt using LangChain """


def get_response(llm, prompt):
    """
    This function takes an LLM instance and a prompt, and returns the full
    AIMessage object generated by the model.
    Args:
        llm: A loaded LangChain LLM object.
        prompt (str): The input text to send to the model.
    Returns:
        AIMessage: The full response message generated by the LLM.
    """
    return llm.invoke(prompt)
